CREATE TABLE [MAESTRO].[Persona] (
    [PersonaId]                INT           IDENTITY (1, 1) NOT NULL,
    [Nombre]                   VARCHAR (70)  NOT NULL,
    [ApePaterno]               VARCHAR (70)  NOT NULL,
    [ApeMaterno]               VARCHAR (70)  NOT NULL,
    [NombreCompleto]           VARCHAR (250) NOT NULL,
    [Apodo]                    VARCHAR (50)  NULL,
    [NumeroDocumento]          VARCHAR (12)  NOT NULL,
    [Sexo]                     CHAR (1)      NOT NULL,
    [Email]                    VARCHAR (100) NULL,
    [FechaNacimiento]          DATE          NULL,
    [Direccion]                VARCHAR (300) NULL,
    [DireccionRef]             VARCHAR (300) NULL,
    [Celular]                  VARCHAR (10)  NULL,
    [EstadoCivilId]            INT           NULL,
    [Apoderado]                VARCHAR (300) NULL,
    [ApoderadoDNI]             VARCHAR (8)   NULL,
    [ApoderadoCelular]         VARCHAR (15)  NULL,
    [ApoderadoParentescoId]    INT           NULL,
    [Activo]                   BIT           NOT NULL,
    [NroHijos]                 INT           CONSTRAINT [DF_Persona_NroHijos] DEFAULT ((0)) NOT NULL,
    [CentroTrabajo]            VARCHAR (150) NULL,
    [PuestoCargo]              VARCHAR (150) NULL,
    [PersonaReferenciaId]      INT           NULL,
    [TipoAlimentacionId]       INT           NULL,
    [AlergiaEnfermedad]        VARCHAR (500) NULL,
    [IndTerapiaPsicologica]    BIT           CONSTRAINT [DF_Persona_IndTerapiaPsicologica] DEFAULT ((0)) NOT NULL,
    [DxTerapiaPsicologica]     VARCHAR (500) NULL,
    [FechaTerapiaPsicologica]  DATE          NULL,
    [IndTerapiaPsiquiatrica]   BIT           CONSTRAINT [DF_Persona_IndTerapiaPsiquiatrica] DEFAULT ((0)) NOT NULL,
    [DxTerapiaPsiquiatrica]    VARCHAR (500) NULL,
    [FechaTerapiaPsiquiatrica] DATE          NULL,
    [Nota]                     VARCHAR (500) NULL,
    [UsuarioRegId]             INT           NULL,
    [FechaReg]                 DATETIME      NULL,
    [IndWari]                  BIT           CONSTRAINT [DF_Persona_IndWari] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK__Persona__7C34D3033A147184] PRIMARY KEY CLUSTERED ([PersonaId] ASC)
);

